#
server:
  port: 8181

logging:
  level:
    org.springframework.security.*: trace

spring:
  application:
    name: AuthorizationServer

  jpa:
    hibernate.ddl-auto: validate
    show-sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/auth_server_app_db
    username: auth_server_app_db_user
    password: mysql@18Rajat
    driver-class-name: com.mysql.cj.jdbc.Driver

  security:
    user:
      name: user
      password: password
#    oauth2:
#      authorizationServer:
#        client:
#          oidc-client:
#            registration:
#              client-id: "oidc-client"
#              client-secret: "$2a$15$/fakG2indFgjkOL0k2fET.kyhK/QbNSWhYIeFKeK2vc5nuqJAOhwe"
#              client-authentication-methods:
#                - "client_secret_basic"
#              authorization-grant-types:
#                - "authorization_code"
#                - "refresh_token"
#              redirect-uris:
#                - "https://oauth.pstmn.io/v1/callbackt"
#              post-logout-redirect-uris:
#                - "https://oauth.pstmn.io/v1/callback"
#              scopes:
#                - "openid"
#                - "profile"
#            require-authorization-consent: true